services:
  - type: web
    name: whatsapp-auto-reply
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/.puppeteer_cache